import AeroChopperImage from './assets/Product/Aero Chopper.png';
import AeroChopperBanner from './assets/Product/Aero Chopper banner.png';
import AeroChopperLiteImage from './assets/Product/Aero Chopper Lite.png';
import AeroChopperLiteBanner from './assets/Product/Aero Chopper Lite.png';
import AeroChopperPlusImage from './assets/Product/Aero Chopper plus.png';
import AeroChopperPlusBanner from './assets/Product/Aero Chopper Plus banner.png';
import AeroSupremeProImage from './assets/Product/Aero Supreme Pro.png';
import AeroSupremeProBanner from './assets/Product/Aero Supreme Pro banner.png';
import AeroSupremeImage from './assets/Product/Aero Supreme.png';
import AeroSupremeBanner from './assets/Product/Aero Supreme banner.png';
import AeroSupremePlusImage from './assets/Product/Aero Supreme Plus.png';
import AeroSupremePlusBanner from './assets/Product/Aero Supreme Plus banner.png';
import AeroPlusImage from './assets/Product/Aero plus.png';
import AeroPlusBanner from './assets/Product/Aero Plus banner.png';
import AeroImage from './assets/Product/Aero .png';
import AeroBanner from './assets/Product/Aero .png';

export const products = [
  {
    id: 1,
    slug: "aero-chopper",
    category: "High Speed Scooters",
    name: "Aero Chopper",
    shortDescription: "Premium electric scooter with strong performance, long-range battery, and modern features for confident daily commuting.",
    description: "Aero Chopper combines power, range, and smart safety in a sleek package. Its 2500W motor delivers strong acceleration, while the 3.0 kWh battery supports up to 130 km per charge. Dual disc brakes, tubeless tyres, and LED lighting keep the ride stable and secure.",
    range: "130 km",
    topSpeed: "70 km/h",
    battery: "3.0 kWh Lithium-ion",
    chargingTime: "3-4 hrs",
    motor: "2500W BLDC",
    brakes: "Dual Disc",
    tyres: "Tubeless 12 inch",
    warranty: "3 Years",
    colors: ["#000000", "#ffffff", "#6B3CC9"],
    accentColor: "#6B3CC9",
    image: AeroChopperImage,
    banner: AeroChopperBanner,
    gallery: [AeroChopperImage, AeroChopperPlusImage, AeroSupremeProImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm", "Reverse Mode"],
  },
  {
    id: 2,
    slug: "aero-chopper-plus",
    category: "High Speed Scooters",
    name: "Aero Chopper Plus",
    shortDescription: "High-speed scooter with upgraded power, extended range, and refined comfort for everyday adventure.",
    description: "Aero Chopper Plus adds stronger acceleration and better efficiency for riders who want more from each trip. With a 3000W motor, 150 km range, and ABS brakes, it offers a balanced mix of speed, safety, and comfort.",
    range: "150 km",
    topSpeed: "80 km/h",
    battery: "3.5 kWh Lithium-ion",
    chargingTime: "3.5-4.5 hrs",
    motor: "3000W BLDC",
    brakes: "Dual Disc with ABS",
    tyres: "Tubeless 12 inch",
    warranty: "3 Years",
    colors: ["#000000", "#87CEEB", "#ffffff"],
    accentColor: "#87CEEB",
    image: AeroChopperPlusImage,
    banner: AeroChopperPlusBanner,
    gallery: [AeroChopperPlusImage, AeroChopperImage, AeroSupremeProImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm", "Reverse Mode", "Regenerative Braking"],
  },
  {
    id: 3,
    slug: "aero-supreme-pro",
    category: "High Speed Scooters",
    name: "Aero Supreme Pro",
    shortDescription: "Flagship model with premium styling, advanced tech, and strong performance for riders seeking the best.",
    description: "Aero Supreme Pro delivers a premium EV experience with robust performance and smart features. Its 3200W motor, 160 km range, and ABS braking system make it ideal for riders who want comfort, control, and standout design.",
    range: "160 km",
    topSpeed: "85 km/h",
    battery: "4.0 kWh Lithium-ion",
    chargingTime: "4-5 hrs",
    motor: "3200W BLDC",
    brakes: "Dual Disc with ABS",
    tyres: "Tubeless 13 inch",
    warranty: "3 Years",
    colors: ["#DC2626", "#000000", "#ffffff"],
    accentColor: "#DC2626",
    image: AeroSupremeProImage,
    banner: AeroSupremeProBanner,
    gallery: [AeroSupremeProImage, AeroChopperPlusImage, AeroSupremeImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm", "Reverse Mode", "Regenerative Braking", "Smart Connect"],
  },
  {
    id: 4,
    slug: "aero-supreme",
    category: "High Speed Scooters",
    name: "Aero Supreme",
    shortDescription: "Reliable daily commuter with smart design, comfortable handling, and efficient everyday performance.",
    description: "Aero Supreme is built for smooth city commuting. With a 2000W motor, 120 km range, and practical safety features, it offers dependable performance without compromising on style or comfort.",
    range: "120 km",
    topSpeed: "65 km/h",
    battery: "2.8 kWh Lithium-ion",
    chargingTime: "3 hrs",
    motor: "2000W BLDC",
    brakes: "Front Disc, Rear Drum",
    tyres: "Tubeless 12 inch",
    warranty: "2 Years",
    colors: ["#DC2626", "#000000", "#ffffff"],
    accentColor: "#DC2626",
    image: AeroSupremeImage,
    banner: AeroSupremeBanner,
    gallery: [AeroSupremeImage, AeroSupremeProImage, AeroChopperImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm"],
  },
  {
    id: 5,
    slug: "aero-supreme-plus",
    category: "High Speed Scooters",
    name: "Aero Supreme Plus",
    shortDescription: "Enhanced commuter scooter with extra comfort, stronger range, and useful everyday features.",
    description: "Aero Supreme Plus adds more range and convenience for riders who want a polished daily experience. Its 2500W motor, 140 km battery range, and reverse mode make it a practical choice for modern urban travel.",
    range: "140 km",
    topSpeed: "75 km/h",
    battery: "3.2 kWh Lithium-ion",
    chargingTime: "3.5 hrs",
    motor: "2500W BLDC",
    brakes: "Dual Disc",
    tyres: "Tubeless 12 inch",
    warranty: "3 Years",
    colors: ["#FFD700", "#000000", "#ffffff"],
    accentColor: "#FFD700",
    image: AeroSupremePlusImage,
    banner: AeroSupremePlusBanner,
    gallery: [AeroSupremePlusImage, AeroSupremeProImage, AeroChopperPlusImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm", "Reverse Mode"],
  },
  {
    id: 6,
    slug: "aero-plus",
    category: "High Speed Scooters",
    name: "Aero Plus",
    shortDescription: "Stylish and efficient scooter designed for smart urban travel with dependable everyday performance.",
    description: "Aero Plus brings a modern look and practical performance together. Its 1800W motor, 110 km range, and quick charging make it a smart option for riders seeking balance, efficiency, and simplicity.",
    range: "110 km",
    topSpeed: "60 km/h",
    battery: "2.5 kWh Lithium-ion",
    chargingTime: "2.5-3 hrs",
    motor: "1800W BLDC",
    brakes: "Front Disc, Rear Drum",
    tyres: "Tubeless 12 inch",
    warranty: "2 Years",
    colors: ["#C0C0C0", "#000000", "#ffffff"],
    accentColor: "#C0C0C0",
    image: AeroPlusImage,
    banner: AeroPlusBanner,
    gallery: [AeroPlusImage, AeroSupremeImage, AeroChopperImage],
    features: ["LED Headlights", "Digital Display"],
  },
  {
    id: 7,
    slug: "aero-chopper-lite",
    category: "Low Speed Scooters",
    name: "Aero Chopper Lite",
    shortDescription: "Compact and efficient city scooter for short trips, errands, and everyday commuting.",
    description: "Aero Chopper Lite is ideal for city travel with a light frame, easy handling, and a practical range. Its 250W motor and 70 km battery range make it a simple, eco-friendly choice for daily use.",
    range: "70 km",
    topSpeed: "25 km/h",
    battery: "1.5 kWh Lithium-ion",
    chargingTime: "2 hrs",
    motor: "250W BLDC",
    brakes: "Drum Brakes",
    tyres: "Tubeless 10 inch",
    warranty: "2 Years",
    colors: ["#F97316", "#000000", "#ffffff"],
    accentColor: "#F97316",
    image: AeroChopperLiteImage,
    banner: AeroChopperLiteBanner,
    gallery: [AeroChopperLiteImage, AeroChopperImage, AeroSupremeImage],
    features: ["LED Headlights", "Analog Display"],
  },
  {
    id: 8,
    slug: "aero",
    category: "Low Speed Scooters",
    name: "Aero",
    shortDescription: "Agile and sporty low-speed scooter designed for quick urban rides with everyday practicality.",
    description: "Aero offers a fun and efficient way to move around the city. With a 350W motor, 80 km range, and smart safety features, it is a reliable companion for daily errands and quick trips.",
    range: "80 km",
    topSpeed: "25 km/h",
    battery: "1.8 kWh Lithium-ion",
    chargingTime: "2-2.5 hrs",
    motor: "350W BLDC",
    brakes: "Front Disc, Rear Drum",
    tyres: "Tubeless 10 inch",
    warranty: "2 Years",
    colors: ["#DC2626", "#000000", "#ffffff"],
    accentColor: "#DC2626",
    image: AeroImage,
    banner: AeroBanner,
    gallery: [AeroImage, AeroChopperImage, AeroSupremeImage],
    features: ["LED Headlights", "Digital Display", "Anti-theft Alarm"],
  },
];

export const technologies = [
  { id: 1, name: "Lithium Battery", icon: "🔋", description: "High-performance lithium-ion batteries with long life and fast charging capability." },
  { id: 2, name: "BLDC Motor", icon: "⚡", description: "Brushless DC motors for efficient power delivery and smooth performance." },
  { id: 3, name: "Fast Charging", icon: "🔌", description: "Advanced fast charging technology to get you back on the road quickly." },
  { id: 4, name: "Smart Controller", icon: "🎛️", description: "Intelligent controller system for optimal performance and efficiency." },
  { id: 5, name: "Regenerative Braking", icon: "🛑", description: "Recover energy while braking to extend your range." },
  { id: 6, name: "Digital Display", icon: "📱", description: "Modern digital display with all essential information at a glance." },
  { id: 7, name: "Smart Lock", icon: "🔐", description: "Advanced smart lock system for enhanced security and convenience." },
  { id: 8, name: "Reverse Mode", icon: "🔄", description: "Easy reverse mode for effortless parking and maneuvering." },
  { id: 9, name: "Anti Theft", icon: "🛡️", description: "Comprehensive anti-theft system to protect your vehicle." },
  { id: 10, name: "LED Lighting", icon: "💡", description: "Bright and energy-efficient LED lighting for better visibility." },
];

export const whyAeroVolt = [
  { id: 1, title: "Premium Quality", description: "Crafted with the finest materials and cutting-edge manufacturing." },
  { id: 2, title: "Long Battery Life", description: "Advanced battery technology for extended range and durability." },
  { id: 3, title: "Best Mileage", description: "Industry-leading efficiency for maximum distance per charge." },
  { id: 4, title: "Fast Charging", description: "Quick charging capabilities to minimize downtime." },
  { id: 5, title: "Advanced Technology", description: "Innovative features that set new standards in EV industry." },
  { id: 6, title: "Eco Friendly", description: "Zero emissions, contributing to a cleaner environment." },
  { id: 7, title: "Affordable Maintenance", description: "Low maintenance costs compared to traditional vehicles." },
  { id: 8, title: "Reliable Service", description: "Dedicated service network for complete peace of mind." },
  { id: 9, title: "Warranty Support", description: "Comprehensive warranty coverage on all our products." },
];

export const galleryImages = [
  { id: 1, url: AeroChopperImage, category: "scooters" },
  { id: 2, url: AeroChopperPlusImage, category: "scooters" },
  { id: 3, url: AeroSupremeProImage, category: "scooters" },
  { id: 4, url: AeroSupremeImage, category: "scooters" },
  { id: 5, url: AeroSupremePlusImage, category: "scooters" },
  { id: 6, url: AeroPlusImage, category: "scooters" },
  { id: 7, url: AeroChopperLiteImage, category: "scooters" },
  { id: 8, url: AeroImage, category: "scooters" },
];
